name: Daily Upload

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the bot
        env:
          GOOGLE_CLIENT_SECRET_JSON: ${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}
        run: |
          mkdir -p app/creds
          echo "$GOOGLE_CLIENT_SECRET_JSON" > app/creds/client_secret.json
          python3 app/main.py

