name: Daily Reddit to YouTube Shorts

on:
  schedule:
    - cron: '0 3 * * *'  # setiap jam 10 pagi WIB
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python reddit-youtube-bot/app/main.py
